import type { Metadata } from 'next';

import localFont from 'next/font/local';
import { Inter } from 'next/font/google';

import './globals.css';
import { Nav } from './components';

const inter = Inter({ subsets: ['latin'] });

const bigNoodle = localFont({
  src: [
    {
      path: '../../public/fonts/big_noodle_titling_oblique.ttf',
      style: 'italic'
    },
    {
      path: '../../public/fonts/big_noodle_titling.ttf',
      style: 'normal'
    }
  ],
  variable: '--font-big-noodle'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${bigNoodle.variable} ${inter.className}`}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
